---
title: "Extracting Masters Data"
author: "Richard G. Gardiner"
date: "1/3/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Loading data and Packages

```{r}
library(tidyverse)
library(readxl)

legislative_control <- read_excel("data/Full Legislative Control.xlsx")

political_culture <- read_csv("data/political culture.csv")

professional <- read_csv("data/ncsl professionalization.csv")

ideology <- read_csv("data/pivoted_branches.csv")
```

```{r}
years <- 1990:2018

legislative_control_long <- legislative_control %>%
  gather(`1990`, `1991`, `1992`, `1993`, `1994`, `1995`, `1996`, `1997`, `1998`, `1999`, `2000`,
         `2001`, `2002`, `2003`, `2004`, `2005`, `2006`, `2007`, `2008`, `2009`, `2010`, `2011`,
         `2012`, `2013`, `2014`, `2015`, `2016`, `2017`, `2018`,
         key = "year", value = "unified")

legislative_control_long
```

# Manipulating Ideology

Need to create ideology scores for the odd years then combine them all!
```{r}
ideology <- ideology %>%
  filter(Year >= 1994)

ideology

ideology_1995 <- ideology %>%
  filter(Year == 1994) %>%
  mutate(Year = 1995)

ideology_1997 <- ideology %>%
  filter(Year == 1996) %>%
  mutate(Year = 1997)

ideology_1999 <- ideology %>%
  filter(Year == 1998) %>%
  mutate(Year = 1999)

ideology_2001 <- ideology %>%
  filter(Year == 2000) %>%
  mutate(Year = 2001)

ideology_2003 <- ideology %>%
  filter(Year == 2002) %>%
  mutate(Year = 2003)

ideology_2005 <- ideology %>%
  filter(Year == 2004) %>%
  mutate(Year = 2005)

ideology_2007 <- ideology %>%
  filter(Year == 2006) %>%
  mutate(Year = 2007)

ideology_2009 <- ideology %>%
  filter(Year == 2008) %>%
  mutate(Year = 2009)

ideology_2011 <- ideology %>%
  filter(Year == 2010) %>%
  mutate(Year = 2011)

ideology_2011

full_ideology <- rbind(ideology, ideology_1995, ideology_1997, ideology_1999, ideology_2001, ideology_2003, ideology_2005, ideology_2007,
                       ideology_2009, ideology_2011) %>%
  filter(!(State %in% "fd")) %>%
  group_by(State, Year) %>%
  arrange(State, Year)

full_ideology
```

