---
title: "Model"
author: "Richard G. Gardiner"
date: "2/20/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Data and Packages

When you start looking at the model, look at [David's Tidy Tuesday project](https://mobile.twitter.com/drob/status/1082318029168566273?s=21). Also check out [this post](https://hockey-graphs.com/2019/01/07/quantifying-differences-between-the-regular-season-and-playoffs-using-survival-analysis/?blogsub=confirming#subscribe-blog).

```{r, packages}
library(tidyverse)
library(survival)
library(survminer)
library(broom)
library(scales)
library(devtools)
library(ggfortify)
```

```{r}
full_dataset <- read_csv("data/all_years_all_variables.csv")
head(full_dataset)

full_dataset <- full_dataset %>%
  filter(Override == 1) %>%
  mutate(Year = Year + 0.01)
```

Here I am adding the absolute distance variables:

```{r}
full_dataset$court_gov_dist <- abs(full_dataset$judicial - full_dataset$governor)
full_dataset$court_lower_dist <- abs(full_dataset$judicial - full_dataset$lower)
full_dataset$court_upper_dist <- abs(full_dataset$judicial - full_dataset$upper)
```


## Initial Analysis

```{r}
initial <- coxph(formula = Surv(case_year, Year, Override) ~ partisan,
                 data = full_dataset)
summary(initial)
```


```{r}
fit <- survfit(formula = Surv(case_year, Year, Override) ~ partisan,
                 data = full_dataset)
ggsurvplot(fit, data = full_dataset, risk.table = TRUE)
```

```{r}
tidy(fit) %>%
  ggplot(aes(time, estimate, color = strata)) +
  geom_line() +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .2)
```


```{r}
appointed <- survfit(formula = Surv(case_year, Year, Override) ~ appointed,
                 data = full_dataset)

tidy(appointed) %>%
  ggplot(aes(time, estimate, color = strata)) +
  geom_line() +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .2)
```


## Larger models

### Introducing ideology
```{r}
full <- coxph(formula = Surv(case_year, Year, Override) ~ partisan +
                non_partisan + appoint_reelect + lower + upper,
                 data = full_dataset)

summary(full) # not great results for me.  Wrong direction
```



```{r}
full_fit <- survfit(formula = Surv(case_year, Year, Override) ~ partisan +
                non_partisan + appoint_reelect + court_lower_dist +
                court_upper_dist,
                data = full_dataset)

# doesn't seem to work becasue of multiple covariates
tidy(full_fit) %>%
  ggplot(aes(time, estimate)) +
  geom_line() +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .2)
```


```{r}
cox_fit <- survfit(full)

autoplot(cox_fit)
```


### adding in interaction terms

```{r}
full_dataset$partisan_ideology_gov <- full_dataset$partisan * full_dataset$court_gov_dist
full_dataset$partisan_ideology_upper <- full_dataset$partisan * full_dataset$court_upper_dist
full_dataset$partisan_ideology_lower <- full_dataset$partisan * full_dataset$court_lower_dist

full_dataset$nonpartisan_ideology_gov <- full_dataset$non_partisan * full_dataset$court_gov_dist
full_dataset$nonpartisan_ideology_upper <- full_dataset$non_partisan * full_dataset$court_upper_dist
full_dataset$nonpartisan_ideology_lower <- full_dataset$non_partisan * full_dataset$court_lower_dist

full_dataset$retention_ideology_gov <- full_dataset$appoint_reelect * full_dataset$court_gov_dist
full_dataset$retention_ideology_upper <- full_dataset$appoint_reelect * full_dataset$court_upper_dist
full_dataset$retention_ideology_lower <- full_dataset$appoint_reelect * full_dataset$court_lower_dist
```

```{r}
interactions <- coxph(formula = Surv(case_year, Year, Override) ~ partisan +
                non_partisan + appoint_reelect + lower + upper + 
                partisan_ideology_lower + partisan_ideology_upper +
                nonpartisan_ideology_lower + nonpartisan_ideology_upper +
                retention_ideology_lower + retention_ideology_upper,
                data = full_dataset)

summary(interactions)
```

### Controls
```{r}
controls <- coxph(formula = Surv(case_year, Year, Override) ~ partisan +
                non_partisan + appoint_reelect + lower + upper + 
                partisan_ideology_lower + partisan_ideology_upper +
                nonpartisan_ideology_lower + nonpartisan_ideology_upper +
                retention_ideology_lower + retention_ideology_upper +
                agency + classact + Moralistic + Traditionalistic +
                Professionalization + unified,
                data = full_dataset)

summary(controls)
```


```{r}

control_fit <- survfit(formula = Surv(case_year, Year, Override) ~ partisan +
                non_partisan + appoint_reelect + lower + upper + 
                partisan_ideology_lower + partisan_ideology_upper +
                nonpartisan_ideology_lower + nonpartisan_ideology_upper +
                retention_ideology_lower + retention_ideology_upper +
                agency + classact + Moralistic + Traditionalistic +
                Professionalization + unified,
                data = full_dataset)



# doesn't seem to work becasue of multiple covariates
tidy(full_fit) %>%
  ggplot(aes(time, estimate)) +
  geom_line() +
  geom_ribbon(aes(ymin = conf.low, ymax = conf.high), alpha = .2)
```







