---
title: "Partisanship"
author: "Richard G. Gardiner"
date: "3/22/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## data and packages

```{r}
library(tidyverse)
library(readxl)
library(haven)
```

```{r}
original <- read_excel("partisan.xlsx")
later <- read_excel("later partisan.xlsx")
```

```{r}
full_legislative_control <- original %>%
  gather(Year, control, -State) %>%
  mutate(RepublicanLegslature = ifelse(control == "Rep", 1, 0),
         SplitLegislature = ifelse(control == "Split", 1, 0)) %>%
  select(-control) %>%
  rbind(later) %>%
  filter(Year > 1994) %>%
  mutate(Year = as.numeric(Year))
```

```{r}
pajid <- read_dta("pajid")
```


```{r, pajid}
seats <- pajid %>%
  filter(year > 1994) %>%
  group_by(year, state) %>%
  summarize(n = n())
  
number_dems <- pajid %>%
  filter(year > 1994) %>%
  group_by(year, state) %>%
  summarize(num_dems <- sum(justicepartyID)) %>%
  rename(num_dems = 3)

majority_dems <- number_dems %>%
  left_join(seats, by = c("state", "year")) %>%
  mutate(majority_dems = if_else(num_dems > (.5 * n), 1, 0))
```



```{r}
partisanship <- full_legislative_control %>%
  left_join(majority_dems, by = c("State" = "state", "Year" = "year")) %>%
  mutate(republican_court = if_else(majority_dems == 0, 1, 0),
         ideologically_similary = if_else(
           RepublicanLegslature == republican_court, 1, 0)) %>%
  select(-num_dems, -n, -majority_dems) 
```


```{r}
# write_csv(partisanship, "partisan_control.csv")
```







